# Generated by Django 4.2.4 on 2023-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solution", "0004_rename_custmer_reviews_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("prise", models.IntegerField()),
                ("pric1", models.TextField()),
                ("pric2", models.TextField()),
                ("pric3", models.TextField()),
                ("pric4", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
