# Generated by Django 4.2.4 on 2023-11-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solution", "0005_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("title", models.CharField(max_length=5000)),
                ("prise", models.IntegerField()),
                ("pric1", models.CharField(max_length=5000)),
                ("pric2", models.CharField(max_length=5000)),
                ("pric3", models.CharField(max_length=5000)),
                ("pric4", models.CharField(max_length=5000)),
                ("pric5", models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name="Pricing",
        ),
    ]
